name: deploy on cloud run

on:
  push:
    branches: "main"

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: imagefront
      PROJECT_ID: clvfront
      SERVICE: clvfront
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Install dependencies
        run: npm ci

      - name: check repository for lint errors
        run: npm run lint


      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
          
      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/$SERVICE/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/$SERVICE/$IMAGE_NAME:latest
          
      - name : Deploy Image to Cloud Run
        run : gcloud run deploy $SERVICE --image europe-west1-docker.pkg.dev/$PROJECT_ID/$SERVICE/$IMAGE_NAME:latest --region europe-west1 --allow-unauthenticated